{% set name = "eemont" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49340c1b489d2ecf05a1f0fe0e0e6a451bad0e2025920daf09773429cc7d06d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - geopy
    - numpy
    - pandas
    - python >=3.6
    - python-box
    - requests

test:
  imports:
    - eemont

about:
  home: https://github.com/davemlz/eemont
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package that extends Google Earth Engine
  doc_url: https://eemont.readthedocs.io/
  dev_url: https://github.com/davemlz/eemont

extra:
  recipe-maintainers:
    - davemlz
