{% set name = "eemont" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3650c7feb955a59e749b3f469ddb197367f737b73ef8e8e62a4609d3ebb61f3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - earthengine-api
    - ee_extra >=0.0.14
    - geopy
    - numpy
    - pandas
    - python >=3.6
    - python-box >=6.0.0
    - requests

test:
  imports:
    - eemont

about:
  home: https://github.com/davemlz/eemont
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package that extends Google Earth Engine
  doc_url: https://eemont.readthedocs.io/
  dev_url: https://github.com/davemlz/eemont

extra:
  recipe-maintainers:
    - davemlz
